[env]
GOPROXY = "https://proxy.golang.org,direct"

[tools]
go = "{{ exec(command=`awk '/^go / {print $2}' go.mod`) }}"

[tasks.setup]
description = "Download dependencies"
run = "scripts/setup.sh"

[tasks.test]
depends = ["setup"]
description = "Run tests"
run = "scripts/test.sh"

[tasks.lint]
depends = ["setup"]
description = "Lint"
run = "scripts/lint.sh"
