name: CI

on: [push, workflow_dispatch]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: Setup
        run: mise run setup
      - name: Test
        run: mise run test
      - name: Lint
        run: mise run lint
